### YamlMime:Yaml
ms.openlocfilehash: 5812f3b4670b326bfe96fe2c2520b546525d462f
ms.sourcegitcommit: a5f49f50d5a19def8ee79289670482bc90b5f0a7
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/02/2019
ms.locfileid: "33556586"
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
