### YamlMime:Yaml
ms.openlocfilehash: 3deb84251a078e6eb83cd1fc3ba901ada93f46d7
ms.sourcegitcommit: ab01e18a0d4e60d00731a5f0ae82face835a3cce
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/21/2020
ms.locfileid: "43613005"
default:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true
  resolved_paths: []
  cache_manifest: false
  extract_css: false
  static_assets_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .tiff
  - .ico
  - .svg
  - .eot
  - .otf
  - .ttf
  - .woff
  - .woff2
  extensions:
  - .mjs
  - .js
  - .sass
  - .scss
  - .css
  - .module.sass
  - .module.scss
  - .module.css
  - .png
  - .svg
  - .gif
  - .jpeg
  - .jpg
development:
  <<:
    source_path: app/javascript
    source_entry_path: packs
    public_root_path: public
    public_output_path: packs
    cache_path: tmp/cache/webpacker
    check_yarn_integrity: false
    webpack_compile_output: true
    resolved_paths: []
    cache_manifest: false
    extract_css: false
    static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
    extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  compile: true
  check_yarn_integrity: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      Access-Control-Allow-Origin: '*'
    watch_options:
      ignored: '**/node_modules/**'
test:
  <<:
    source_path: app/javascript
    source_entry_path: packs
    public_root_path: public
    public_output_path: packs
    cache_path: tmp/cache/webpacker
    check_yarn_integrity: false
    webpack_compile_output: true
    resolved_paths: []
    cache_manifest: false
    extract_css: false
    static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
    extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  compile: true
  public_output_path: packs-test
production:
  <<:
    source_path: app/javascript
    source_entry_path: packs
    public_root_path: public
    public_output_path: packs
    cache_path: tmp/cache/webpacker
    check_yarn_integrity: false
    webpack_compile_output: true
    resolved_paths: []
    cache_manifest: false
    extract_css: false
    static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
    extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  compile: false
  extract_css: true
  cache_manifest: true
