### YamlMime:Yaml
ms.openlocfilehash: 4948a90acdd07aba52cacebcbfc061eb20febc41
ms.sourcegitcommit: a5f49f50d5a19def8ee79289670482bc90b5f0a7
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/02/2019
ms.locfileid: "33556614"
inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
  - bin/**
  - db/**/**
