### YamlMime:Yaml
ms.openlocfilehash: 176e5c554bcc42a16f908191b9a8ae0c86eafc53
ms.sourcegitcommit: ab01e18a0d4e60d00731a5f0ae82face835a3cce
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/21/2020
ms.locfileid: "43613001"
Layout/AccessModifierIndentation:
  Exclude:
  - bin/bundle
Layout/ArgumentAlignment:
  Exclude:
  - bin/webpack
  - bin/webpack-dev-server
Layout/EmptyLineAfterGuardClause:
  Exclude:
  - bin/bundle
Layout/EndOfLine:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
  - config/environments/production.rb
Metrics/AbcSize:
  Max: 18
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/MethodLength:
  Max: 13
Metrics/PerceivedComplexity:
  Max: 9
Style/ClassAndModuleChildren:
  Exclude:
  - test/channels/application_cable/connection_test.rb
  - test/test_helper.rb
Style/Documentation:
  Exclude:
  - spec/**/*
  - test/**/*
  - app/helpers/application_helper.rb
  - app/mailers/application_mailer.rb
  - app/models/application_record.rb
  - config/application.rb
Style/ExpandPathArguments:
  Exclude:
  - bin/bundle
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Exclude:
  - bin/bundle
Style/PerlBackrefs:
  Exclude:
  - bin/bundle
Style/RedundantBegin:
  Exclude:
  - bin/yarn
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/StderrPuts:
  Exclude:
  - bin/yarn
Style/StringLiterals:
  Exclude:
  - bin/bundle
  - bin/webpack
  - bin/webpack-dev-server
  - bin/yarn
  - config/environments/production.rb
  - config/puma.rb
  - test/application_system_test_case.rb
  - test/channels/application_cable/connection_test.rb
Style/SymbolArray:
  EnforcedStyle: brackets
Layout/LineLength:
  Max: 190
