### YamlMime:Yaml
ms.openlocfilehash: ff965ec9254e5d328f31126bf81dad8d57ff9dcd
ms.sourcegitcommit: 0a09ce80c160c2435146e5aa48928cad29d752ad
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 03/07/2019
ms.locfileid: "30547443"
Layout/EndOfLine:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
  - config/environments/production.rb
Style/ClassAndModuleChildren:
  Exclude:
  - test/test_helper.rb
Style/Documentation:
  Exclude:
  - spec/**/*
  - test/**/*
  - app/helpers/application_helper.rb
  - app/mailers/application_mailer.rb
  - app/models/application_record.rb
  - config/application.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MixinUsage:
  Exclude:
  - bin/setup
  - bin/update
Style/StderrPuts:
  Exclude:
  - bin/yarn
Style/StringLiterals:
  Exclude:
  - bin/yarn
  - config/environments/production.rb
  - config/puma.rb
  - test/application_system_test_case.rb
Style/SymbolArray:
  EnforcedStyle: brackets
Metrics/LineLength:
  Max: 112
