### YamlMime:Yaml
ms.openlocfilehash: 233e814552b4d773381e002f325fbe3eaaa9e591
ms.sourcegitcommit: 0a09ce80c160c2435146e5aa48928cad29d752ad
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 03/07/2019
ms.locfileid: "30547226"
default:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  database: db/development.sqlite3
test:
  <<:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  database: db/test.sqlite3
production:
  <<:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  database: db/production.sqlite3
