### YamlMime:Yaml
ms.openlocfilehash: b6ecba7b8fb1d9fabf98be9fa05cdff0a9aab48f
ms.sourcegitcommit: 0a09ce80c160c2435146e5aa48928cad29d752ad
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 03/07/2019
ms.locfileid: "30547408"
development:
  adapter: async
test:
  adapter: async
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: graph-tutorial_production
